POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "guilherme",
    "password": "12345"
}

###
POST http://localhost:3000/cadastrar
Content-Type: application/json

{
    "username": "guilherme",
    "password": "12345"
}

###
POST http://localhost:3000/delete
Content-Type: application/json

{
    "username": "nathalia",
    "password": "12345",
    "id": "4b0ec83d-393f-41dd-acb2-da87d3d6cc5a"
}

###
POST http://localhost:3000/task
Content-Type: application/json

{
    "username": "guilherme",
    "id": "c4b2b3f5-12d5-41cb-a892-48011665ed1a"
}

###
POST http://localhost:3000/addTask
Content-Type: application/json

{
    "task_id": "79209bc8-d497-411d-aba3-0b591de4f2de",
    "task_userid": "6b55520d-cfc3-4b53-bd50-7370fb7963e7",
    "task_task": "Teste adicionando segunda task",
    "task_date": "2025-09-30 00:00:00",
    "task_state": "open"
}