POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "guilherme",
    "password": "12345"
}

###
POST http://localhost:3000/cadastrar
Content-Type: application/json

{
    "username": "teste",
    "password": "12345"
}

###
POST http://localhost:3000/delete
Content-Type: application/json

{
    "username": "nathalia",
    "password": "12345",
    "id": "4b0ec83d-393f-41dd-acb2-da87d3d6cc5a"
}

###
POST https://dashnote.onrender.com/task
Content-Type: application/json

{
    "username": "guilherme",
    "id": "6b55520d-cfc3-4b53-bd50-7370fb7963e7"
}

###
POST http://localhost:3000/addTask
Content-Type: application/json

{
    "task_userid": "6b55520d-cfc3-4b53-bd50-7370fb7963e7",
    "task_task": "Segundo teste server",
    "task_date": "2025-09-30 00:00:00",
    "task_state": "open"
}

###
DELETE http://localhost:3000/deleteTask/5b6115b6-7b8c-4790-8d5f-1469da5682f7